### ISSUE TITLE
Continue work Well done

### ISSUE THREAD

**Issue by Eatric** [chaplin89/ClarifierEx#1]
This is a good thing, I'm waiting for the continuation

**Comment by chaplin89** [comment]
For the moment this project is in a semi-abandoned state because I had other ideas that can help the deobfuscation and make it more reliable. I'm trying to concretize these ideas before getting back to develop ClarifierEx. BTW it should handle the most basic protections, as I said in the description, but I guess it would require some refactoring in order to work (I've surely messed up something with the latest commits).
